#!/bin/bash

hostname="$(hostname)"
timezone="$(timedatectl | grep 'Time zone' | awk '{print $3 $4 $5}')"
os="$(lsb_release -s -d)"
date="$(date '+ %d %b %Y %T')"
uptime="$(uptime -p)"
uptime_sec="$(awk '{print $1}' /proc/uptime)" 
ip="$(hostname -i | awk '{print $1}')"
netmask="$(ifconfig | grep netmask | awk '{print $4}')"
gateway="$(ip route | grep default | awk '{print $3}')"
mem="$(free -m | grep "Mem" | awk '{printf "%.3f Gb\n", $2/1024}')"
mem_used="$(free -m | grep "Mem" | awk '{printf "%.3f Gb\n", $3/1024}')"
mem_free="$(free -m | grep "Mem" | awk '{printf "%.3f Gb\n", $4/1024}')"
space_root="$(df | grep "/$" | awk '{printf "%.2f Mb\n", $2}')"
space_used="$(df | grep "/$" | awk '{printf "%.2f Mb\n", $3}')"
space_free="$(df | grep "/$" | awk '{printf "%.2f Mb\n", $4}')"

echo -e "${BG_N}${FG_N}HOSTNAME${BG_NC}${NC}=${BG_V}${FG_V}$hostname${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}TIMEZONE${BG_NC}${NC} = ${BG_V}${FG_V}$timezone${BG_NC}${NC}"
echo -e  "${BG_N}${FG_N}USER${BG_NC}${NC} = ${BG_V}${FG_V}$USER${BG_NC}${NC}"
echo -e  "${BG_N}${FG_N}OS${BG_NC}${NC} = ${BG_V}${FG_V}$os${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}DATE${BG_NC}${NC} = ${BG_V}${FG_V}$date${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}UPTIME${BG_NC}${NC} = ${BG_V}${FG_V}$uptime${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}UPTIME_SEC${BG_NC}${NC} = ${BG_V}${FG_V}$uptime_sec${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}IP${BG_NC}${NC} = ${BG_V}${FG_V}$ip${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}MASK${BG_NC}${NC} = ${BG_V}${FG_V}$netmask${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}GATEWAY${BG_NC}${NC} = ${BG_V}${FG_V}$gateway${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}AM_TOTAL${BG_NC}${NC} = ${BG_V}${FG_V}$mem${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}RAM_USED${BG_NC}${NC} = ${BG_V}${FG_V}$mem_used${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}RAM_FREE${BG_NC}${NC} = ${BG_V}${FG_V}$mem_free${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}SPACE_ROOT${BG_NC}${NC} = ${BG_V}${FG_V}$space_root${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}SPACE_ROOT_USED${BG_NC}${NC} = ${BG_V}${FG_V}$space_used${BG_NC}${NC}"
echo -e "${BG_N}${FG_N}SPACE_ROOT_FREE${BG_NC}${NC} = ${BG_V}${FG_V}$space_free${BG_NC}${NC}"
